### ISSUE TITLE
Listen for the player hitting the obstacle

### ISSUE THREAD

**Issue by StevenR152** [codersuk/ludum-dare-44#16]
What do we do with the obstacle?
What do we do with the dragon?

**Comment by bramburn** [comment]
Keep the obstacle the same.
I think like you said make the dragon flash, bounce up and fall back a few steps

**Comment by bramburn** [comment]
Or instead of falling back the bounty hunter moves a few steps forward

**Comment by StevenR152** [comment]
I made the player get pushed left by the object till they move.

Still an issue that landing on the object counts as hitting it so you can't stand on a log either. Maybe another ghost entity to be the platform 1px above the rock/log?

**Comment by StevenR152** [comment]
I actually think when the player hits the top of a log they should slide left , because the rock is moving left it would be unnatural if they did not slide on it? 

Maybe this will look wrong when the dragon is running?

**Comment by bramburn** [comment]
@StevenR152 what do you wanna do?

**Comment by StevenR152** [comment]
It seems like this is now resolved itself, the player keeps running on the top of both logs and rocks.
